### ISSUE TITLE
閲覧者がタグを設定する機能が欲しい

### ISSUE THREAD

**Issue by kmtr** [rusts/team#41]
例えば `ci` というタグで、 jenkinsについての記事があったときに、
`jenkins` というタグを閲覧者が付与する機能が欲しい。

案1
通常のタグとは別に、閲覧ユーザー用のタグ空間を作る
作成者以外でも個人用のタグを追加、削除できる。
記事自体のタグは作成者以外は変更できない。

案2
編集リクエストを送れるようにする。作成者以外はタグを追加、削除できない。

案3
全てのユーザーがタグを追加・削除できる。

**Comment by dongri** [comment]
なるほど！
タグだけではなく案２がいいかも知らないですね

**Comment by dongri** [comment]
完了。案３で
