### ISSUE TITLE
Tweet機能追加したらどうですかね？

### ISSUE THREAD

**Issue by dongri** [rusts/team#48]
Cc: @kmtr

**Comment by kmtr** [comment]
Twitter的なミニ投稿機能ということですか？
新しい投稿機能を増やすよりも、ユーザー単位のタイムライン(投稿、日報、コメント)が見られると良い気がします。

**Comment by dongri** [comment]
前はユーザー単位のタイムラインみたいのがあったんですが、投稿と日報が混ざってると若干日報が邪魔で見にくかったのでユーザープロフィールページで投稿と日報を分けました。

**Comment by dongri** [comment]
ワークしなさそうなのでclose
