### ISSUE TITLE
SearchにNippoがヒットしすぎる

### ISSUE THREAD

**Issue by keitaj** [rusts/team#58]
SearchにNippoがヒットしすぎるので、ヒットさせないように特定のタグを除外するなどのオプション欲しいです。

**Comment by dongri** [comment]
ふざけるな！

**Comment by dongri** [comment]
<img width="387" alt="screen shot 2018-07-02 at 19 32 42" src="https://user-images.githubusercontent.com/878993/42159451-be5fa212-7e2e-11e8-9e9d-ffc42ec08392.png">

PostをクリックするとNippoを除いたものだけ出るようにしました
